version: '3.8'

services:
  postgres:
    image: postgres
    container_name: deal-postgres
    environment:
      POSTGRES_USER: deal
      POSTGRES_DB: deal_db
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d deal_db"]
      interval: 10s
      timeout: 5s
    restart: unless-stopped

volumes:
  postgres_data: